/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XlsxStatistikAustria;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportBefunddaten;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportKloezel;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.records.XlsxStatistikAustriaRecord;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.records.XmlReportBefunddatenRecord;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.records.XmlReportKloezelRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>prostate</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<XlsxStatistikAustriaRecord, Integer> IDENTITY_XLSX_STATISTIK_AUSTRIA = Identities0.IDENTITY_XLSX_STATISTIK_AUSTRIA;
    public static final Identity<XmlReportBefunddatenRecord, Integer> IDENTITY_XML_REPORT_BEFUNDDATEN = Identities0.IDENTITY_XML_REPORT_BEFUNDDATEN;
    public static final Identity<XmlReportKloezelRecord, Integer> IDENTITY_XML_REPORT_KLOEZEL = Identities0.IDENTITY_XML_REPORT_KLOEZEL;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<XlsxStatistikAustriaRecord> PROSTATE_XLSX_STATISTIK_AUSTRIA_PKEY = UniqueKeys0.PROSTATE_XLSX_STATISTIK_AUSTRIA_PKEY;
    public static final UniqueKey<XmlReportBefunddatenRecord> GOOGLE_COLON_PKEY = UniqueKeys0.GOOGLE_COLON_PKEY;
    public static final UniqueKey<XmlReportKloezelRecord> XML_REPORT_KLOEZEL_ID_PKEY = UniqueKeys0.XML_REPORT_KLOEZEL_ID_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<XlsxStatistikAustriaRecord, Integer> IDENTITY_XLSX_STATISTIK_AUSTRIA = Internal.createIdentity(XlsxStatistikAustria.XLSX_STATISTIK_AUSTRIA, XlsxStatistikAustria.XLSX_STATISTIK_AUSTRIA.ID);
        public static Identity<XmlReportBefunddatenRecord, Integer> IDENTITY_XML_REPORT_BEFUNDDATEN = Internal.createIdentity(XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN, XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN.ID);
        public static Identity<XmlReportKloezelRecord, Integer> IDENTITY_XML_REPORT_KLOEZEL = Internal.createIdentity(XmlReportKloezel.XML_REPORT_KLOEZEL, XmlReportKloezel.XML_REPORT_KLOEZEL.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<XlsxStatistikAustriaRecord> PROSTATE_XLSX_STATISTIK_AUSTRIA_PKEY = Internal.createUniqueKey(XlsxStatistikAustria.XLSX_STATISTIK_AUSTRIA, "prostate_xlsx_statistik_austria_pkey", XlsxStatistikAustria.XLSX_STATISTIK_AUSTRIA.ID);
        public static final UniqueKey<XmlReportBefunddatenRecord> GOOGLE_COLON_PKEY = Internal.createUniqueKey(XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN, "google_colon_pkey", XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN.ID);
        public static final UniqueKey<XmlReportKloezelRecord> XML_REPORT_KLOEZEL_ID_PKEY = Internal.createUniqueKey(XmlReportKloezel.XML_REPORT_KLOEZEL, "xml_report_kloezel_id_pkey", XmlReportKloezel.XML_REPORT_KLOEZEL.ID);
    }
}
