/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in prostate
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>prostate.xlsx_statistik_austria_id_seq</code>
     */
    public static final Sequence<Long> XLSX_STATISTIK_AUSTRIA_ID_SEQ = new SequenceImpl<Long>("xlsx_statistik_austria_id_seq", Prostate.PROSTATE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>prostate.xml_report_befunddaten_id_seq</code>
     */
    public static final Sequence<Long> XML_REPORT_BEFUNDDATEN_ID_SEQ = new SequenceImpl<Long>("xml_report_befunddaten_id_seq", Prostate.PROSTATE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>prostate.xml_report_kloezel_id_seq</code>
     */
    public static final Sequence<Long> XML_REPORT_KLOEZEL_ID_SEQ = new SequenceImpl<Long>("xml_report_kloezel_id_seq", Prostate.PROSTATE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
