/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.ReportProstateData;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XlsxStatistikAustria;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportBefunddaten;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportKloezel;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in prostate
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>prostate.report_prostate_data</code>.
     */
    public static final ReportProstateData REPORT_PROSTATE_DATA = at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.ReportProstateData.REPORT_PROSTATE_DATA;

    /**
     * The table <code>prostate.xlsx_statistik_austria</code>.
     */
    public static final XlsxStatistikAustria XLSX_STATISTIK_AUSTRIA = at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XlsxStatistikAustria.XLSX_STATISTIK_AUSTRIA;

    /**
     * The table <code>prostate.xml_report_befunddaten</code>.
     */
    public static final XmlReportBefunddaten XML_REPORT_BEFUNDDATEN = at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN;

    /**
     * The table <code>prostate.xml_report_kloezel</code>.
     */
    public static final XmlReportKloezel XML_REPORT_KLOEZEL = at.medunigraz.pathology.bibbox.datatools.jooq.prostate.tables.XmlReportKloezel.XML_REPORT_KLOEZEL;
}
