/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryLinkDictionary;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictionaryLinkDictionaryRecord extends TableRecordImpl<DictionaryLinkDictionaryRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 845222360;

    /**
     * Setter for <code>saat.dictionary_link_dictionary.edge_id</code>.
     */
    public void setEdgeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>saat.dictionary_link_dictionary.edge_id</code>.
     */
    public Integer getEdgeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>saat.dictionary_link_dictionary.child_dictionary_id</code>.
     */
    public void setChildDictionaryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>saat.dictionary_link_dictionary.child_dictionary_id</code>.
     */
    public Integer getChildDictionaryId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>saat.dictionary_link_dictionary.dictionary_id</code>.
     */
    public void setDictionaryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>saat.dictionary_link_dictionary.dictionary_id</code>.
     */
    public Integer getDictionaryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY.EDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY.CHILD_DICTIONARY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY.DICTIONARY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getChildDictionaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDictionaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getChildDictionaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDictionaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryLinkDictionaryRecord value1(Integer value) {
        setEdgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryLinkDictionaryRecord value2(Integer value) {
        setChildDictionaryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryLinkDictionaryRecord value3(Integer value) {
        setDictionaryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryLinkDictionaryRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictionaryLinkDictionaryRecord
     */
    public DictionaryLinkDictionaryRecord() {
        super(DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY);
    }

    /**
     * Create a detached, initialised DictionaryLinkDictionaryRecord
     */
    public DictionaryLinkDictionaryRecord(Integer edgeId, Integer childDictionaryId, Integer dictionaryId) {
        super(DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY);

        set(0, edgeId);
        set(1, childDictionaryId);
        set(2, dictionaryId);
    }
}
