/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Dictionary2FindingsLink;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Diseases;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Findings;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Patient;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>patient_repository</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DICTIONARY2_FINDINGS_LINK_ID_PK = Indexes0.DICTIONARY2_FINDINGS_LINK_ID_PK;
    public static final Index DISEASE_ID_PK = Indexes0.DISEASE_ID_PK;
    public static final Index AURA_INDEX_HASH = Indexes0.AURA_INDEX_HASH;
    public static final Index AURA_INDEX_UNIQUE = Indexes0.AURA_INDEX_UNIQUE;
    public static final Index FINDING_ID_PK = Indexes0.FINDING_ID_PK;
    public static final Index FINDINGS_PATIENT_ID_BTREE = Indexes0.FINDINGS_PATIENT_ID_BTREE;
    public static final Index ORGAN_HASH = Indexes0.ORGAN_HASH;
    public static final Index ORGAN_ZUORDNUNG_HASH = Indexes0.ORGAN_ZUORDNUNG_HASH;
    public static final Index PATIENT_ID_PK = Indexes0.PATIENT_ID_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DICTIONARY2_FINDINGS_LINK_ID_PK = Internal.createIndex("dictionary2_findings_link_id_pk", Dictionary2FindingsLink.DICTIONARY2_FINDINGS_LINK, new OrderField[] { Dictionary2FindingsLink.DICTIONARY2_FINDINGS_LINK.DICTIONARY2_FINDINGS_LINK_ID }, true);
        public static Index DISEASE_ID_PK = Internal.createIndex("disease_id_pk", Diseases.DISEASES, new OrderField[] { Diseases.DISEASES.DISEASE_ID }, true);
        public static Index AURA_INDEX_HASH = Internal.createIndex("aura_index_hash", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.AURA_INDEX }, false);
        public static Index AURA_INDEX_UNIQUE = Internal.createIndex("aura_index_unique", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.AURA_INDEX }, true);
        public static Index FINDING_ID_PK = Internal.createIndex("finding_id_pk", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.FINDING_ID }, true);
        public static Index FINDINGS_PATIENT_ID_BTREE = Internal.createIndex("findings_patient_id_btree", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.PATIENT_ID }, false);
        public static Index ORGAN_HASH = Internal.createIndex("organ_hash", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.ORGAN }, false);
        public static Index ORGAN_ZUORDNUNG_HASH = Internal.createIndex("organ_zuordnung_hash", Findings.FINDINGS, new OrderField[] { Findings.FINDINGS.ORGAN_ZUORDNUNG }, false);
        public static Index PATIENT_ID_PK = Internal.createIndex("patient_id_pk", Patient.PATIENT, new OrderField[] { Patient.PATIENT.PATIENT_ID }, true);
    }
}
