/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Dictionary2FindingsLink;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Diseases;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.DiseasesEvaluation;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Findings;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.FindingsEvaluation;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Patient;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in patient_repository
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>patient_repository.dictionary2_findings_link</code>.
     */
    public static final Dictionary2FindingsLink DICTIONARY2_FINDINGS_LINK = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Dictionary2FindingsLink.DICTIONARY2_FINDINGS_LINK;

    /**
     * The table <code>patient_repository.diseases</code>.
     */
    public static final Diseases DISEASES = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Diseases.DISEASES;

    /**
     * The table <code>patient_repository.diseases_evaluation</code>.
     */
    public static final DiseasesEvaluation DISEASES_EVALUATION = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.DiseasesEvaluation.DISEASES_EVALUATION;

    /**
     * The table <code>patient_repository.findings</code>.
     */
    public static final Findings FINDINGS = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Findings.FINDINGS;

    /**
     * The table <code>patient_repository.findings_evaluation</code>.
     */
    public static final FindingsEvaluation FINDINGS_EVALUATION = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.FindingsEvaluation.FINDINGS_EVALUATION;

    /**
     * The table <code>patient_repository.patient</code>.
     */
    public static final Patient PATIENT = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Patient.PATIENT;
}
