/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.PatientRepository;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.records.FindingsEvaluationRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FindingsEvaluation extends TableImpl<FindingsEvaluationRecord> {

    private static final long serialVersionUID = 844646103;

    /**
     * The reference instance of <code>patient_repository.findings_evaluation</code>
     */
    public static final FindingsEvaluation FINDINGS_EVALUATION = new FindingsEvaluation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FindingsEvaluationRecord> getRecordType() {
        return FindingsEvaluationRecord.class;
    }

    /**
     * The column <code>patient_repository.findings_evaluation.finding_id</code>.
     */
    public final TableField<FindingsEvaluationRecord, Integer> FINDING_ID = createField("finding_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.icd10</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> ICD10 = createField("icd10", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.icdo</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> ICDO = createField("icdo", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.t</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> T = createField("t", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.n</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> N = createField("n", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.m</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> M = createField("m", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.g</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> G = createField("g", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.r</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> R = createField("r", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.l</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> L = createField("l", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.v</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> V = createField("v", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>patient_repository.findings_evaluation.command</code>.
     */
    public final TableField<FindingsEvaluationRecord, String> COMMAND = createField("command", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>patient_repository.findings_evaluation</code> table reference
     */
    public FindingsEvaluation() {
        this(DSL.name("findings_evaluation"), null);
    }

    /**
     * Create an aliased <code>patient_repository.findings_evaluation</code> table reference
     */
    public FindingsEvaluation(String alias) {
        this(DSL.name(alias), FINDINGS_EVALUATION);
    }

    /**
     * Create an aliased <code>patient_repository.findings_evaluation</code> table reference
     */
    public FindingsEvaluation(Name alias) {
        this(alias, FINDINGS_EVALUATION);
    }

    private FindingsEvaluation(Name alias, Table<FindingsEvaluationRecord> aliased) {
        this(alias, aliased, null);
    }

    private FindingsEvaluation(Name alias, Table<FindingsEvaluationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FindingsEvaluation(Table<O> child, ForeignKey<O, FindingsEvaluationRecord> key) {
        super(child, key, FINDINGS_EVALUATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PatientRepository.PATIENT_REPOSITORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluation as(String alias) {
        return new FindingsEvaluation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluation as(Name alias) {
        return new FindingsEvaluation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FindingsEvaluation rename(String name) {
        return new FindingsEvaluation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FindingsEvaluation rename(Name name) {
        return new FindingsEvaluation(name, null);
    }
}
