/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.RezeptorNames;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RezeptorNamesRecord extends UpdatableRecordImpl<RezeptorNamesRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 802907850;

    /**
     * Setter for <code>patient_repository_saat_mamma.rezeptor_names.rezeptor_names_id</code>.
     */
    public void setRezeptorNamesId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patient_repository_saat_mamma.rezeptor_names.rezeptor_names_id</code>.
     */
    public Integer getRezeptorNamesId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patient_repository_saat_mamma.rezeptor_names.findings_token_id</code>.
     */
    public void setFindingsTokenId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>patient_repository_saat_mamma.rezeptor_names.findings_token_id</code>.
     */
    public Integer getFindingsTokenId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>patient_repository_saat_mamma.rezeptor_names.rezeptor_name</code>.
     */
    public void setRezeptorName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>patient_repository_saat_mamma.rezeptor_names.rezeptor_name</code>.
     */
    public String getRezeptorName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RezeptorNames.REZEPTOR_NAMES.REZEPTOR_NAMES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RezeptorNames.REZEPTOR_NAMES.FINDINGS_TOKEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RezeptorNames.REZEPTOR_NAMES.REZEPTOR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRezeptorNamesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFindingsTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRezeptorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRezeptorNamesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFindingsTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRezeptorName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RezeptorNamesRecord value1(Integer value) {
        setRezeptorNamesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RezeptorNamesRecord value2(Integer value) {
        setFindingsTokenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RezeptorNamesRecord value3(String value) {
        setRezeptorName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RezeptorNamesRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RezeptorNamesRecord
     */
    public RezeptorNamesRecord() {
        super(RezeptorNames.REZEPTOR_NAMES);
    }

    /**
     * Create a detached, initialised RezeptorNamesRecord
     */
    public RezeptorNamesRecord(Integer rezeptorNamesId, Integer findingsTokenId, String rezeptorName) {
        super(RezeptorNames.REZEPTOR_NAMES);

        set(0, rezeptorNamesId);
        set(1, findingsTokenId);
        set(2, rezeptorName);
    }
}
