/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate_cv;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_cv.tables.DiagnosisSelection;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in prostate_cv
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>prostate_cv.diagnosis_selection</code>.
     */
    public static final DiagnosisSelection DIAGNOSIS_SELECTION = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_cv.tables.DiagnosisSelection.DIAGNOSIS_SELECTION;
}
