/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.AdoptScannFiles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdoptScannFilesRecord extends TableRecordImpl<AdoptScannFilesRecord> implements Record12<String, String, String, String, String, String, String, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 800861642;

    /**
     * Setter for <code>colon_crc.adopt_scann_files.row.names</code>.
     */
    public void setRowNames(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.row.names</code>.
     */
    public String getRowNames() {
        return (String) get(0);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Patient.ID</code>.
     */
    public void setPatientId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Patient.ID</code>.
     */
    public String getPatientId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Case.ID</code>.
     */
    public void setCaseId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Case.ID</code>.
     */
    public String getCaseId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Block.ID</code>.
     */
    public void setBlockId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Block.ID</code>.
     */
    public String getBlockId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Slide.ID</code>.
     */
    public void setSlideId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Slide.ID</code>.
     */
    public String getSlideId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Scan.ID</code>.
     */
    public void setScanId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Scan.ID</code>.
     */
    public String getScanId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Barcode</code>.
     */
    public void setBarcode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Barcode</code>.
     */
    public String getBarcode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Pfad</code>.
     */
    public void setPfad(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Pfad</code>.
     */
    public String getPfad() {
        return (String) get(7);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.Staining</code>.
     */
    public void setStaining(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.Staining</code>.
     */
    public String getStaining() {
        return (String) get(8);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.WSI.ID</code>.
     */
    public void setWsiId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.WSI.ID</code>.
     */
    public String getWsiId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.MRXSID</code>.
     */
    public void setMrxsid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.MRXSID</code>.
     */
    public String getMrxsid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>colon_crc.adopt_scann_files.DSPACE.URL</code>.
     */
    public void setDspaceUrl(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>colon_crc.adopt_scann_files.DSPACE.URL</code>.
     */
    public Boolean getDspaceUrl() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.ROW_NAMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.PATIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.CASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.BLOCK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.SLIDE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.SCAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.BARCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.PFAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.STAINING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.WSI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.MRXSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return AdoptScannFiles.ADOPT_SCANN_FILES.DSPACE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRowNames();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSlideId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getScanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBarcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPfad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getStaining();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getWsiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getMrxsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getDspaceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRowNames();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSlideId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getScanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBarcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPfad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStaining();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getWsiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMrxsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getDspaceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value1(String value) {
        setRowNames(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value2(String value) {
        setPatientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value3(String value) {
        setCaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value4(String value) {
        setBlockId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value5(String value) {
        setSlideId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value6(String value) {
        setScanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value7(String value) {
        setBarcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value8(String value) {
        setPfad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value9(String value) {
        setStaining(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value10(String value) {
        setWsiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value11(String value) {
        setMrxsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord value12(Boolean value) {
        setDspaceUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdoptScannFilesRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdoptScannFilesRecord
     */
    public AdoptScannFilesRecord() {
        super(AdoptScannFiles.ADOPT_SCANN_FILES);
    }

    /**
     * Create a detached, initialised AdoptScannFilesRecord
     */
    public AdoptScannFilesRecord(String rowNames, String patientId, String caseId, String blockId, String slideId, String scanId, String barcode, String pfad, String staining, String wsiId, String mrxsid, Boolean dspaceUrl) {
        super(AdoptScannFiles.ADOPT_SCANN_FILES);

        set(0, rowNames);
        set(1, patientId);
        set(2, caseId);
        set(3, blockId);
        set(4, slideId);
        set(5, scanId);
        set(6, barcode);
        set(7, pfad);
        set(8, staining);
        set(9, wsiId);
        set(10, mrxsid);
        set(11, dspaceUrl);
    }
}
