/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.Icd10table;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Icd10tableRecord extends TableRecordImpl<Icd10tableRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -1467819597;

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.icd10table.icd10id</code>.
     */
    public void setIcd10id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.icd10table.icd10id</code>.
     */
    public Integer getIcd10id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.icd10table.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.icd10table.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.icd10table.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.icd10table.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.icd10table.inclusive</code>.
     */
    public void setInclusive(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.icd10table.inclusive</code>.
     */
    public String getInclusive() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.icd10table.exclusive</code>.
     */
    public void setExclusive(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.icd10table.exclusive</code>.
     */
    public String getExclusive() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Icd10table.ICD10TABLE.ICD10ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Icd10table.ICD10TABLE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Icd10table.ICD10TABLE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Icd10table.ICD10TABLE.INCLUSIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Icd10table.ICD10TABLE.EXCLUSIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIcd10id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInclusive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getExclusive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIcd10id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInclusive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExclusive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord value1(Integer value) {
        setIcd10id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord value4(String value) {
        setInclusive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord value5(String value) {
        setExclusive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Icd10tableRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Icd10tableRecord
     */
    public Icd10tableRecord() {
        super(Icd10table.ICD10TABLE);
    }

    /**
     * Create a detached, initialised Icd10tableRecord
     */
    public Icd10tableRecord(Integer icd10id, String code, String description, String inclusive, String exclusive) {
        super(Icd10table.ICD10TABLE);

        set(0, icd10id);
        set(1, code);
        set(2, description);
        set(3, inclusive);
        set(4, exclusive);
    }
}
