/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.Keyvaluetable;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeyvaluetableRecord extends TableRecordImpl<KeyvaluetableRecord> implements Record7<String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = 957179468;

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.keyvalueid</code>.
     */
    public void setKeyvalueid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.keyvalueid</code>.
     */
    public String getKeyvalueid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.sourcetype</code>.
     */
    public void setSourcetype(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.sourcetype</code>.
     */
    public String getSourcetype() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.sourceid</code>.
     */
    public void setSourceid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.sourceid</code>.
     */
    public String getSourceid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.key</code>.
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.note</code>.
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.keyvaluetable.note</code>.
     */
    public String getNote() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Keyvaluetable.KEYVALUETABLE.KEYVALUEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Keyvaluetable.KEYVALUETABLE.SOURCETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Keyvaluetable.KEYVALUETABLE.SOURCEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Keyvaluetable.KEYVALUETABLE.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Keyvaluetable.KEYVALUETABLE.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Keyvaluetable.KEYVALUETABLE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Keyvaluetable.KEYVALUETABLE.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKeyvalueid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSourcetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSourceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKeyvalueid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSourcetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSourceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value1(String value) {
        setKeyvalueid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value2(String value) {
        setSourcetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value3(String value) {
        setSourceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value4(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value5(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value6(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord value7(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyvaluetableRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KeyvaluetableRecord
     */
    public KeyvaluetableRecord() {
        super(Keyvaluetable.KEYVALUETABLE);
    }

    /**
     * Create a detached, initialised KeyvaluetableRecord
     */
    public KeyvaluetableRecord(String keyvalueid, String sourcetype, String sourceid, String key, String value, Timestamp timestamp, String note) {
        super(Keyvaluetable.KEYVALUETABLE);

        set(0, keyvalueid);
        set(1, sourcetype);
        set(2, sourceid);
        set(3, key);
        set(4, value);
        set(5, timestamp);
        set(6, note);
    }
}
