/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.PatienttableBack;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatienttableBackRecord extends TableRecordImpl<PatienttableBackRecord> implements Record12<String, Long, String, String, String, String, String, Integer, String, String, String, Short> {

    private static final long serialVersionUID = -236147576;

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.patientid</code>.
     */
    public void setPatientid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.patientid</code>.
     */
    public String getPatientid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.vpatientid</code>.
     */
    public void setVpatientid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.vpatientid</code>.
     */
    public Long getVpatientid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateofbirth</code>.
     */
    public void setDateofbirth(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateofbirth</code>.
     */
    public String getDateofbirth() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateofdeath</code>.
     */
    public void setDateofdeath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateofdeath</code>.
     */
    public String getDateofdeath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.icdn</code>.
     */
    public void setIcdn(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.icdn</code>.
     */
    public String getIcdn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.icde</code>.
     */
    public void setIcde(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.icde</code>.
     */
    public String getIcde() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.gender</code>.
     */
    public void setGender(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.gender</code>.
     */
    public String getGender() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.survivalindays</code>.
     */
    public void setSurvivalindays(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.survivalindays</code>.
     */
    public Integer getSurvivalindays() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.survivalstatus</code>.
     */
    public void setSurvivalstatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.survivalstatus</code>.
     */
    public String getSurvivalstatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.cutofday</code>.
     */
    public void setCutofday(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.cutofday</code>.
     */
    public String getCutofday() {
        return (String) get(9);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateoffirstdiagnosis</code>.
     */
    public void setDateoffirstdiagnosis(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.dateoffirstdiagnosis</code>.
     */
    public String getDateoffirstdiagnosis() {
        return (String) get(10);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.ageatcutof</code>.
     */
    public void setAgeatcutof(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.patienttable_back.ageatcutof</code>.
     */
    public Short getAgeatcutof() {
        return (Short) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, Long, String, String, String, String, String, Integer, String, String, String, Short> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, Long, String, String, String, String, String, Integer, String, String, String, Short> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PatienttableBack.PATIENTTABLE_BACK.PATIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PatienttableBack.PATIENTTABLE_BACK.VPATIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PatienttableBack.PATIENTTABLE_BACK.DATEOFBIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PatienttableBack.PATIENTTABLE_BACK.DATEOFDEATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PatienttableBack.PATIENTTABLE_BACK.ICDN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PatienttableBack.PATIENTTABLE_BACK.ICDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PatienttableBack.PATIENTTABLE_BACK.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return PatienttableBack.PATIENTTABLE_BACK.SURVIVALINDAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PatienttableBack.PATIENTTABLE_BACK.SURVIVALSTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PatienttableBack.PATIENTTABLE_BACK.CUTOFDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return PatienttableBack.PATIENTTABLE_BACK.DATEOFFIRSTDIAGNOSIS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field12() {
        return PatienttableBack.PATIENTTABLE_BACK.AGEATCUTOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getVpatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDateofbirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDateofdeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIcdn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIcde();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getSurvivalindays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSurvivalstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCutofday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDateoffirstdiagnosis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component12() {
        return getAgeatcutof();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVpatientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateofbirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDateofdeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIcdn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIcde();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getSurvivalindays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSurvivalstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCutofday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDateoffirstdiagnosis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value12() {
        return getAgeatcutof();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value1(String value) {
        setPatientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value2(Long value) {
        setVpatientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value3(String value) {
        setDateofbirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value4(String value) {
        setDateofdeath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value5(String value) {
        setIcdn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value6(String value) {
        setIcde(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value7(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value8(Integer value) {
        setSurvivalindays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value9(String value) {
        setSurvivalstatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value10(String value) {
        setCutofday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value11(String value) {
        setDateoffirstdiagnosis(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord value12(Short value) {
        setAgeatcutof(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatienttableBackRecord values(String value1, Long value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11, Short value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatienttableBackRecord
     */
    public PatienttableBackRecord() {
        super(PatienttableBack.PATIENTTABLE_BACK);
    }

    /**
     * Create a detached, initialised PatienttableBackRecord
     */
    public PatienttableBackRecord(String patientid, Long vpatientid, String dateofbirth, String dateofdeath, String icdn, String icde, String gender, Integer survivalindays, String survivalstatus, String cutofday, String dateoffirstdiagnosis, Short ageatcutof) {
        super(PatienttableBack.PATIENTTABLE_BACK);

        set(0, patientid);
        set(1, vpatientid);
        set(2, dateofbirth);
        set(3, dateofdeath);
        set(4, icdn);
        set(5, icde);
        set(6, gender);
        set(7, survivalindays);
        set(8, survivalstatus);
        set(9, cutofday);
        set(10, dateoffirstdiagnosis);
        set(11, ageatcutof);
    }
}
