/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxx20200705_scannerwebserviceproductive.tables.Slideuploadtable;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlideuploadtableRecord extends TableRecordImpl<SlideuploadtableRecord> implements Record7<Integer, String, Integer, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 892596078;

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadid</code>.
     */
    public void setUploadid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadid</code>.
     */
    public Integer getUploadid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.scanid_fk</code>.
     */
    public void setScanidFk(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.scanid_fk</code>.
     */
    public String getScanidFk() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadready</code>.
     */
    public void setUploadready(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadready</code>.
     */
    public Integer getUploadready() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadstartdate</code>.
     */
    public void setUploadstartdate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadstartdate</code>.
     */
    public Integer getUploadstartdate() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadenddate</code>.
     */
    public void setUploadenddate(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadenddate</code>.
     */
    public Integer getUploadenddate() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadfolder</code>.
     */
    public void setUploadfolder(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.uploadfolder</code>.
     */
    public String getUploadfolder() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.projectid_fk</code>.
     */
    public void setProjectidFk(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>xxx20200705_scannerwebserviceproductive.slideuploadtable.projectid_fk</code>.
     */
    public Integer getProjectidFk() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Slideuploadtable.SLIDEUPLOADTABLE.UPLOADID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Slideuploadtable.SLIDEUPLOADTABLE.SCANID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Slideuploadtable.SLIDEUPLOADTABLE.UPLOADREADY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Slideuploadtable.SLIDEUPLOADTABLE.UPLOADSTARTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Slideuploadtable.SLIDEUPLOADTABLE.UPLOADENDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Slideuploadtable.SLIDEUPLOADTABLE.UPLOADFOLDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Slideuploadtable.SLIDEUPLOADTABLE.PROJECTID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUploadid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getScanidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUploadready();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUploadstartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUploadenddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUploadfolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getProjectidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUploadid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getScanidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUploadready();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUploadstartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUploadenddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUploadfolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getProjectidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value1(Integer value) {
        setUploadid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value2(String value) {
        setScanidFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value3(Integer value) {
        setUploadready(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value4(Integer value) {
        setUploadstartdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value5(Integer value) {
        setUploadenddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value6(String value) {
        setUploadfolder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord value7(Integer value) {
        setProjectidFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlideuploadtableRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SlideuploadtableRecord
     */
    public SlideuploadtableRecord() {
        super(Slideuploadtable.SLIDEUPLOADTABLE);
    }

    /**
     * Create a detached, initialised SlideuploadtableRecord
     */
    public SlideuploadtableRecord(Integer uploadid, String scanidFk, Integer uploadready, Integer uploadstartdate, Integer uploadenddate, String uploadfolder, Integer projectidFk) {
        super(Slideuploadtable.SLIDEUPLOADTABLE);

        set(0, uploadid);
        set(1, scanidFk);
        set(2, uploadready);
        set(3, uploadstartdate);
        set(4, uploadenddate);
        set(5, uploadfolder);
        set(6, projectidFk);
    }
}
