/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc;


import at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.AdoptScannFiles;
import at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.XmlReportBefunddaten;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in colon_crc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>colon_crc.adopt_scann_files</code>.
     */
    public static final AdoptScannFiles ADOPT_SCANN_FILES = at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.AdoptScannFiles.ADOPT_SCANN_FILES;

    /**
     * The table <code>colon_crc.xml_report_befunddaten</code>.
     */
    public static final XmlReportBefunddaten XML_REPORT_BEFUNDDATEN = at.medunigraz.pathology.bibbox.datatools.jooq.colon_crc.tables.XmlReportBefunddaten.XML_REPORT_BEFUNDDATEN;
}
