/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.scannerwebserviceproductive.tables.Inboxtable;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InboxtableRecord extends UpdatableRecordImpl<InboxtableRecord> implements Record7<Integer, String, Boolean, String, Integer, Integer, String> {

    private static final long serialVersionUID = -1130639836;

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.inboxid</code>.
     */
    public void setInboxid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.inboxid</code>.
     */
    public Integer getInboxid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.inboxfolder</code>.
     */
    public void setInboxfolder(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.inboxfolder</code>.
     */
    public String getInboxfolder() {
        return (String) get(1);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.inboxisactive</code>.
     */
    public void setInboxisactive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.inboxisactive</code>.
     */
    public Boolean getInboxisactive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.inboxinfo</code>.
     */
    public void setInboxinfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.inboxinfo</code>.
     */
    public String getInboxinfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.inboxthreads</code>.
     */
    public void setInboxthreads(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.inboxthreads</code>.
     */
    public Integer getInboxthreads() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.projectid_fk</code>.
     */
    public void setProjectidFk(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.projectid_fk</code>.
     */
    public Integer getProjectidFk() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.inboxtable.wpname</code>.
     */
    public void setWpname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.inboxtable.wpname</code>.
     */
    public String getWpname() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Boolean, String, Integer, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Boolean, String, Integer, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Inboxtable.INBOXTABLE.INBOXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Inboxtable.INBOXTABLE.INBOXFOLDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Inboxtable.INBOXTABLE.INBOXISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inboxtable.INBOXTABLE.INBOXINFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Inboxtable.INBOXTABLE.INBOXTHREADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Inboxtable.INBOXTABLE.PROJECTID_FK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Inboxtable.INBOXTABLE.WPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getInboxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getInboxfolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getInboxisactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInboxinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getInboxthreads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getProjectidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInboxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInboxfolder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getInboxisactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInboxinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getInboxthreads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getProjectidFk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value1(Integer value) {
        setInboxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value2(String value) {
        setInboxfolder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value3(Boolean value) {
        setInboxisactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value4(String value) {
        setInboxinfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value5(Integer value) {
        setInboxthreads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value6(Integer value) {
        setProjectidFk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord value7(String value) {
        setWpname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InboxtableRecord values(Integer value1, String value2, Boolean value3, String value4, Integer value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InboxtableRecord
     */
    public InboxtableRecord() {
        super(Inboxtable.INBOXTABLE);
    }

    /**
     * Create a detached, initialised InboxtableRecord
     */
    public InboxtableRecord(Integer inboxid, String inboxfolder, Boolean inboxisactive, String inboxinfo, Integer inboxthreads, Integer projectidFk, String wpname) {
        super(Inboxtable.INBOXTABLE);

        set(0, inboxid);
        set(1, inboxfolder);
        set(2, inboxisactive);
        set(3, inboxinfo);
        set(4, inboxthreads);
        set(5, projectidFk);
        set(6, wpname);
    }
}
