/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.scannerwebserviceproductive.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.scannerwebserviceproductive.tables.Stagingreferenz;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StagingreferenzRecord extends UpdatableRecordImpl<StagingreferenzRecord> implements Record7<Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = 803156813;

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.stageingreferenzid</code>.
     */
    public void setStageingreferenzid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.stageingreferenzid</code>.
     */
    public Integer getStageingreferenzid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.referenzname</code>.
     */
    public void setReferenzname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.referenzname</code>.
     */
    public String getReferenzname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.referenzversion</code>.
     */
    public void setReferenzversion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.referenzversion</code>.
     */
    public String getReferenzversion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.shortdiscription</code>.
     */
    public void setShortdiscription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.shortdiscription</code>.
     */
    public String getShortdiscription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.referenzurl</code>.
     */
    public void setReferenzurl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.referenzurl</code>.
     */
    public String getReferenzurl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.referenzdiscription</code>.
     */
    public void setReferenzdiscription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.referenzdiscription</code>.
     */
    public String getReferenzdiscription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>scannerwebserviceproductive.stagingreferenz.referenzsql</code>.
     */
    public void setReferenzsql(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>scannerwebserviceproductive.stagingreferenz.referenzsql</code>.
     */
    public String getReferenzsql() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Stagingreferenz.STAGINGREFERENZ.STAGEINGREFERENZID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stagingreferenz.STAGINGREFERENZ.REFERENZNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Stagingreferenz.STAGINGREFERENZ.REFERENZVERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Stagingreferenz.STAGINGREFERENZ.SHORTDISCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Stagingreferenz.STAGINGREFERENZ.REFERENZURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Stagingreferenz.STAGINGREFERENZ.REFERENZDISCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Stagingreferenz.STAGINGREFERENZ.REFERENZSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStageingreferenzid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReferenzname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReferenzversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getShortdiscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getReferenzurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReferenzdiscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getReferenzsql();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStageingreferenzid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReferenzname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReferenzversion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getShortdiscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReferenzurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReferenzdiscription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getReferenzsql();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value1(Integer value) {
        setStageingreferenzid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value2(String value) {
        setReferenzname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value3(String value) {
        setReferenzversion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value4(String value) {
        setShortdiscription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value5(String value) {
        setReferenzurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value6(String value) {
        setReferenzdiscription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord value7(String value) {
        setReferenzsql(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StagingreferenzRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StagingreferenzRecord
     */
    public StagingreferenzRecord() {
        super(Stagingreferenz.STAGINGREFERENZ);
    }

    /**
     * Create a detached, initialised StagingreferenzRecord
     */
    public StagingreferenzRecord(Integer stageingreferenzid, String referenzname, String referenzversion, String shortdiscription, String referenzurl, String referenzdiscription, String referenzsql) {
        super(Stagingreferenz.STAGINGREFERENZ);

        set(0, stageingreferenzid);
        set(1, referenzname);
        set(2, referenzversion);
        set(3, shortdiscription);
        set(4, referenzurl);
        set(5, referenzdiscription);
        set(6, referenzsql);
    }
}
