/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.colon_imports;


import at.medunigraz.pathology.bibbox.datatools.jooq.colon_imports.tables.HistonumberEnumberMap;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>colon_imports</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HISTONUMBER_ENUMBER_MAP_PKEY = Indexes0.HISTONUMBER_ENUMBER_MAP_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index HISTONUMBER_ENUMBER_MAP_PKEY = Internal.createIndex("histonumber_enumber_map_pkey", HistonumberEnumberMap.HISTONUMBER_ENUMBER_MAP, new OrderField[] { HistonumberEnumberMap.HISTONUMBER_ENUMBER_MAP.ID }, true);
    }
}
