/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.colon_imports;


import at.medunigraz.pathology.bibbox.datatools.jooq.colon_imports.tables.HistonumberEnumberMap;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in colon_imports
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>colon_imports.histonumber_enumber_map</code>.
     */
    public static final HistonumberEnumberMap HISTONUMBER_ENUMBER_MAP = at.medunigraz.pathology.bibbox.datatools.jooq.colon_imports.tables.HistonumberEnumberMap.HISTONUMBER_ENUMBER_MAP;
}
