/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.test.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.test.tables.Donor;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DonorRecord extends UpdatableRecordImpl<DonorRecord> implements Record9<Integer, String, String, String, Date, String, String, Date, String> {

    private static final long serialVersionUID = -1738105628;

    /**
     * Setter for <code>test.donor.doner_id</code>.
     */
    public void setDonerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.donor.doner_id</code>.
     */
    public Integer getDonerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.donor.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.donor.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.donor.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.donor.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.donor.gender</code>.
     */
    public void setGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.donor.gender</code>.
     */
    public String getGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.donor.date_of_birth</code>.
     */
    public void setDateOfBirth(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.donor.date_of_birth</code>.
     */
    public Date getDateOfBirth() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>test.donor.race</code>.
     */
    public void setRace(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.donor.race</code>.
     */
    public String getRace() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.donor.ethnicity</code>.
     */
    public void setEthnicity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.donor.ethnicity</code>.
     */
    public String getEthnicity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test.donor.date_of_death</code>.
     */
    public void setDateOfDeath(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.donor.date_of_death</code>.
     */
    public Date getDateOfDeath() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>test.donor.couse_of_death</code>.
     */
    public void setCouseOfDeath(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.donor.couse_of_death</code>.
     */
    public String getCouseOfDeath() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Date, String, String, Date, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Date, String, String, Date, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Donor.DONOR.DONER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Donor.DONOR.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Donor.DONOR.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Donor.DONOR.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Donor.DONOR.DATE_OF_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Donor.DONOR.RACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Donor.DONOR.ETHNICITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Donor.DONOR.DATE_OF_DEATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Donor.DONOR.COUSE_OF_DEATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDonerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getEthnicity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getDateOfDeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCouseOfDeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDonerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEthnicity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getDateOfDeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCouseOfDeath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value1(Integer value) {
        setDonerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value3(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value4(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value5(Date value) {
        setDateOfBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value6(String value) {
        setRace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value7(String value) {
        setEthnicity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value8(Date value) {
        setDateOfDeath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord value9(String value) {
        setCouseOfDeath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DonorRecord values(Integer value1, String value2, String value3, String value4, Date value5, String value6, String value7, Date value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DonorRecord
     */
    public DonorRecord() {
        super(Donor.DONOR);
    }

    /**
     * Create a detached, initialised DonorRecord
     */
    public DonorRecord(Integer donerId, String firstName, String lastName, String gender, Date dateOfBirth, String race, String ethnicity, Date dateOfDeath, String couseOfDeath) {
        super(Donor.DONOR);

        set(0, donerId);
        set(1, firstName);
        set(2, lastName);
        set(3, gender);
        set(4, dateOfBirth);
        set(5, race);
        set(6, ethnicity);
        set(7, dateOfDeath);
        set(8, couseOfDeath);
    }
}
