/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.tables;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.XxxoldScannerwebserviceproductive;
import at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.tables.records.GoogleslideuploadtableRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Googleslideuploadtable extends TableImpl<GoogleslideuploadtableRecord> {

    private static final long serialVersionUID = 88394272;

    /**
     * The reference instance of <code>xxxold_scannerwebserviceproductive.googleslideuploadtable</code>
     */
    public static final Googleslideuploadtable GOOGLESLIDEUPLOADTABLE = new Googleslideuploadtable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoogleslideuploadtableRecord> getRecordType() {
        return GoogleslideuploadtableRecord.class;
    }

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.uploadid</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, Integer> UPLOADID = createField("uploadid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.scanid_fk</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, String> SCANID_FK = createField("scanid_fk", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.uploadready</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, Integer> UPLOADREADY = createField("uploadready", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.uploadstartdate</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, Integer> UPLOADSTARTDATE = createField("uploadstartdate", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.uploadenddate</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, Integer> UPLOADENDDATE = createField("uploadenddate", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.googleslideuploadtable.uploadfolder</code>.
     */
    public final TableField<GoogleslideuploadtableRecord, String> UPLOADFOLDER = createField("uploadfolder", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>xxxold_scannerwebserviceproductive.googleslideuploadtable</code> table reference
     */
    public Googleslideuploadtable() {
        this(DSL.name("googleslideuploadtable"), null);
    }

    /**
     * Create an aliased <code>xxxold_scannerwebserviceproductive.googleslideuploadtable</code> table reference
     */
    public Googleslideuploadtable(String alias) {
        this(DSL.name(alias), GOOGLESLIDEUPLOADTABLE);
    }

    /**
     * Create an aliased <code>xxxold_scannerwebserviceproductive.googleslideuploadtable</code> table reference
     */
    public Googleslideuploadtable(Name alias) {
        this(alias, GOOGLESLIDEUPLOADTABLE);
    }

    private Googleslideuploadtable(Name alias, Table<GoogleslideuploadtableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Googleslideuploadtable(Name alias, Table<GoogleslideuploadtableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Googleslideuploadtable(Table<O> child, ForeignKey<O, GoogleslideuploadtableRecord> key) {
        super(child, key, GOOGLESLIDEUPLOADTABLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return XxxoldScannerwebserviceproductive.XXXOLD_SCANNERWEBSERVICEPRODUCTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Googleslideuploadtable as(String alias) {
        return new Googleslideuploadtable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Googleslideuploadtable as(Name alias) {
        return new Googleslideuploadtable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Googleslideuploadtable rename(String name) {
        return new Googleslideuploadtable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Googleslideuploadtable rename(Name name) {
        return new Googleslideuploadtable(name, null);
    }
}
