/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.tables;


import at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.XxxoldScannerwebserviceproductive;
import at.medunigraz.pathology.bibbox.datatools.jooq.xxxold_scannerwebserviceproductive.tables.records.ScannertableRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scannertable extends TableImpl<ScannertableRecord> {

    private static final long serialVersionUID = 1170130334;

    /**
     * The reference instance of <code>xxxold_scannerwebserviceproductive.scannertable</code>
     */
    public static final Scannertable SCANNERTABLE = new Scannertable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScannertableRecord> getRecordType() {
        return ScannertableRecord.class;
    }

    /**
     * The column <code>xxxold_scannerwebserviceproductive.scannertable.scannerid</code>.
     */
    public final TableField<ScannertableRecord, String> SCANNERID = createField("scannerid", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.scannertable.scannertype</code>.
     */
    public final TableField<ScannertableRecord, String> SCANNERTYPE = createField("scannertype", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.scannertable.scannermanufacturer</code>.
     */
    public final TableField<ScannertableRecord, String> SCANNERMANUFACTURER = createField("scannermanufacturer", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>xxxold_scannerwebserviceproductive.scannertable.scannerrackslots</code>.
     */
    public final TableField<ScannertableRecord, String> SCANNERRACKSLOTS = createField("scannerrackslots", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>xxxold_scannerwebserviceproductive.scannertable</code> table reference
     */
    public Scannertable() {
        this(DSL.name("scannertable"), null);
    }

    /**
     * Create an aliased <code>xxxold_scannerwebserviceproductive.scannertable</code> table reference
     */
    public Scannertable(String alias) {
        this(DSL.name(alias), SCANNERTABLE);
    }

    /**
     * Create an aliased <code>xxxold_scannerwebserviceproductive.scannertable</code> table reference
     */
    public Scannertable(Name alias) {
        this(alias, SCANNERTABLE);
    }

    private Scannertable(Name alias, Table<ScannertableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Scannertable(Name alias, Table<ScannertableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Scannertable(Table<O> child, ForeignKey<O, ScannertableRecord> key) {
        super(child, key, SCANNERTABLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return XxxoldScannerwebserviceproductive.XXXOLD_SCANNERWEBSERVICEPRODUCTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Scannertable as(String alias) {
        return new Scannertable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Scannertable as(Name alias) {
        return new Scannertable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Scannertable rename(String name) {
        return new Scannertable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scannertable rename(Name name) {
        return new Scannertable(name, null);
    }
}
