/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.Diseases;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseasesRecord extends UpdatableRecordImpl<DiseasesRecord> {

    private static final long serialVersionUID = -695365858;

    /**
     * Setter for <code>patient_repository.diseases.disease_id</code>.
     */
    public void setDiseaseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.disease_id</code>.
     */
    public Integer getDiseaseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patient_repository.diseases.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>patient_repository.diseases.finding_id_diagnosen</code>.
     */
    public void setFindingIdDiagnosen(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.finding_id_diagnosen</code>.
     */
    public String getFindingIdDiagnosen() {
        return (String) get(2);
    }

    /**
     * Setter for <code>patient_repository.diseases.time_diff</code>.
     */
    public void setTimeDiff(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.time_diff</code>.
     */
    public Long getTimeDiff() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>patient_repository.diseases.age</code>.
     */
    public void setAge(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.age</code>.
     */
    public Double getAge() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>patient_repository.diseases.diagnosis</code>.
     */
    public void setDiagnosis(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.diagnosis</code>.
     */
    public String getDiagnosis() {
        return (String) get(5);
    }

    /**
     * Setter for <code>patient_repository.diseases.diagnosis_clean</code>.
     */
    public void setDiagnosisClean(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.diagnosis_clean</code>.
     */
    public String getDiagnosisClean() {
        return (String) get(6);
    }

    /**
     * Setter for <code>patient_repository.diseases.organ</code>.
     */
    public void setOrgan(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.organ</code>.
     */
    public String getOrgan() {
        return (String) get(7);
    }

    /**
     * Setter for <code>patient_repository.diseases.organ_zuordnung</code>.
     */
    public void setOrganZuordnung(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.organ_zuordnung</code>.
     */
    public String getOrganZuordnung() {
        return (String) get(8);
    }

    /**
     * Setter for <code>patient_repository.diseases.doctor</code>.
     */
    public void setDoctor(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.doctor</code>.
     */
    public String getDoctor() {
        return (String) get(9);
    }

    /**
     * Setter for <code>patient_repository.diseases.doctor_id</code>.
     */
    public void setDoctorId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.doctor_id</code>.
     */
    public Integer getDoctorId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>patient_repository.diseases.sender</code>.
     */
    public void setSender(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.sender</code>.
     */
    public String getSender() {
        return (String) get(11);
    }

    /**
     * Setter for <code>patient_repository.diseases.sender_id</code>.
     */
    public void setSenderId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.sender_id</code>.
     */
    public Integer getSenderId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>patient_repository.diseases.nb</code>.
     */
    public void setNb(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.nb</code>.
     */
    public Short getNb() {
        return (Short) get(13);
    }

    /**
     * Setter for <code>patient_repository.diseases.es_anz</code>.
     */
    public void setEsAnz(Short value) {
        set(14, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.es_anz</code>.
     */
    public Short getEsAnz() {
        return (Short) get(14);
    }

    /**
     * Setter for <code>patient_repository.diseases.dict_id_mor</code>.
     */
    public void setDictIdMor(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.dict_id_mor</code>.
     */
    public String getDictIdMor() {
        return (String) get(15);
    }

    /**
     * Setter for <code>patient_repository.diseases.dict_id_top</code>.
     */
    public void setDictIdTop(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.dict_id_top</code>.
     */
    public String getDictIdTop() {
        return (String) get(16);
    }

    /**
     * Setter for <code>patient_repository.diseases.t</code>.
     */
    public void setT(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.t</code>.
     */
    public String getT() {
        return (String) get(17);
    }

    /**
     * Setter for <code>patient_repository.diseases.g</code>.
     */
    public void setG(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.g</code>.
     */
    public String getG() {
        return (String) get(18);
    }

    /**
     * Setter for <code>patient_repository.diseases.m</code>.
     */
    public void setM(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.m</code>.
     */
    public String getM() {
        return (String) get(19);
    }

    /**
     * Setter for <code>patient_repository.diseases.r</code>.
     */
    public void setR(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.r</code>.
     */
    public String getR() {
        return (String) get(20);
    }

    /**
     * Setter for <code>patient_repository.diseases.n</code>.
     */
    public void setN(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.n</code>.
     */
    public String getN() {
        return (String) get(21);
    }

    /**
     * Setter for <code>patient_repository.diseases.l</code>.
     */
    public void setL(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.l</code>.
     */
    public String getL() {
        return (String) get(22);
    }

    /**
     * Setter for <code>patient_repository.diseases.v</code>.
     */
    public void setV(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.v</code>.
     */
    public String getV() {
        return (String) get(23);
    }

    /**
     * Setter for <code>patient_repository.diseases.SCG</code>.
     */
    public void setScg(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.SCG</code>.
     */
    public String getScg() {
        return (String) get(24);
    }

    /**
     * Setter for <code>patient_repository.diseases.organ_test</code>.
     */
    public void setOrganTest(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.organ_test</code>.
     */
    public String getOrganTest() {
        return (String) get(25);
    }

    /**
     * Setter for <code>patient_repository.diseases.average_examination_date</code>.
     */
    public void setAverageExaminationDate(Date value) {
        set(26, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.average_examination_date</code>.
     */
    public Date getAverageExaminationDate() {
        return (Date) get(26);
    }

    /**
     * Setter for <code>patient_repository.diseases.examination_type</code>.
     */
    public void setExaminationType(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>patient_repository.diseases.examination_type</code>.
     */
    public String getExaminationType() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiseasesRecord
     */
    public DiseasesRecord() {
        super(Diseases.DISEASES);
    }

    /**
     * Create a detached, initialised DiseasesRecord
     */
    public DiseasesRecord(Integer diseaseId, Long patientId, String findingIdDiagnosen, Long timeDiff, Double age, String diagnosis, String diagnosisClean, String organ, String organZuordnung, String doctor, Integer doctorId, String sender, Integer senderId, Short nb, Short esAnz, String dictIdMor, String dictIdTop, String t, String g, String m, String r, String n, String l, String v, String scg, String organTest, Date averageExaminationDate, String examinationType) {
        super(Diseases.DISEASES);

        set(0, diseaseId);
        set(1, patientId);
        set(2, findingIdDiagnosen);
        set(3, timeDiff);
        set(4, age);
        set(5, diagnosis);
        set(6, diagnosisClean);
        set(7, organ);
        set(8, organZuordnung);
        set(9, doctor);
        set(10, doctorId);
        set(11, sender);
        set(12, senderId);
        set(13, nb);
        set(14, esAnz);
        set(15, dictIdMor);
        set(16, dictIdTop);
        set(17, t);
        set(18, g);
        set(19, m);
        set(20, r);
        set(21, n);
        set(22, l);
        set(23, v);
        set(24, scg);
        set(25, organTest);
        set(26, averageExaminationDate);
        set(27, examinationType);
    }
}
