/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository.tables.FindingsEvaluation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FindingsEvaluationRecord extends TableRecordImpl<FindingsEvaluationRecord> implements Record11<Integer, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -267974361;

    /**
     * Setter for <code>patient_repository.findings_evaluation.finding_id</code>.
     */
    public void setFindingId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.finding_id</code>.
     */
    public Integer getFindingId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.icd10</code>.
     */
    public void setIcd10(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.icd10</code>.
     */
    public String getIcd10() {
        return (String) get(1);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.icdo</code>.
     */
    public void setIcdo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.icdo</code>.
     */
    public String getIcdo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.t</code>.
     */
    public void setT(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.t</code>.
     */
    public String getT() {
        return (String) get(3);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.n</code>.
     */
    public void setN(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.n</code>.
     */
    public String getN() {
        return (String) get(4);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.m</code>.
     */
    public void setM(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.m</code>.
     */
    public String getM() {
        return (String) get(5);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.g</code>.
     */
    public void setG(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.g</code>.
     */
    public String getG() {
        return (String) get(6);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.r</code>.
     */
    public void setR(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.r</code>.
     */
    public String getR() {
        return (String) get(7);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.l</code>.
     */
    public void setL(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.l</code>.
     */
    public String getL() {
        return (String) get(8);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.v</code>.
     */
    public void setV(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.v</code>.
     */
    public String getV() {
        return (String) get(9);
    }

    /**
     * Setter for <code>patient_repository.findings_evaluation.command</code>.
     */
    public void setCommand(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>patient_repository.findings_evaluation.command</code>.
     */
    public String getCommand() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FindingsEvaluation.FINDINGS_EVALUATION.FINDING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FindingsEvaluation.FINDINGS_EVALUATION.ICD10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FindingsEvaluation.FINDINGS_EVALUATION.ICDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FindingsEvaluation.FINDINGS_EVALUATION.T;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FindingsEvaluation.FINDINGS_EVALUATION.N;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FindingsEvaluation.FINDINGS_EVALUATION.M;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FindingsEvaluation.FINDINGS_EVALUATION.G;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FindingsEvaluation.FINDINGS_EVALUATION.R;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return FindingsEvaluation.FINDINGS_EVALUATION.L;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return FindingsEvaluation.FINDINGS_EVALUATION.V;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return FindingsEvaluation.FINDINGS_EVALUATION.COMMAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFindingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIcd10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIcdo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getT();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getN();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getM();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getG();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getR();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getL();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getV();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCommand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFindingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIcd10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIcdo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getT();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getN();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getM();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getG();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getR();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getL();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getV();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCommand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value1(Integer value) {
        setFindingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value2(String value) {
        setIcd10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value3(String value) {
        setIcdo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value4(String value) {
        setT(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value5(String value) {
        setN(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value6(String value) {
        setM(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value7(String value) {
        setG(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value8(String value) {
        setR(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value9(String value) {
        setL(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value10(String value) {
        setV(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord value11(String value) {
        setCommand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FindingsEvaluationRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FindingsEvaluationRecord
     */
    public FindingsEvaluationRecord() {
        super(FindingsEvaluation.FINDINGS_EVALUATION);
    }

    /**
     * Create a detached, initialised FindingsEvaluationRecord
     */
    public FindingsEvaluationRecord(Integer findingId, String icd10, String icdo, String t, String n, String m, String g, String r, String l, String v, String command) {
        super(FindingsEvaluation.FINDINGS_EVALUATION);

        set(0, findingId);
        set(1, icd10);
        set(2, icdo);
        set(3, t);
        set(4, n);
        set(5, m);
        set(6, g);
        set(7, r);
        set(8, l);
        set(9, v);
        set(10, command);
    }
}
