/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma;


import at.medunigraz.pathology.bibbox.datatools.jooq.DefaultCatalog;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsHer2neu;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsOestrogenrezeptor;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsProgesternrezeptor;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsWithRezeptor;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.RezeptorNames;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRepositorySaatMamma extends SchemaImpl {

    private static final long serialVersionUID = -86444017;

    /**
     * The reference instance of <code>patient_repository_saat_mamma</code>
     */
    public static final PatientRepositorySaatMamma PATIENT_REPOSITORY_SAAT_MAMMA = new PatientRepositorySaatMamma();

    /**
     * The table <code>patient_repository_saat_mamma.findings_her2neu</code>.
     */
    public final FindingsHer2neu FINDINGS_HER2NEU = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsHer2neu.FINDINGS_HER2NEU;

    /**
     * The table <code>patient_repository_saat_mamma.findings_oestrogenrezeptor</code>.
     */
    public final FindingsOestrogenrezeptor FINDINGS_OESTROGENREZEPTOR = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsOestrogenrezeptor.FINDINGS_OESTROGENREZEPTOR;

    /**
     * The table <code>patient_repository_saat_mamma.findings_progesternrezeptor</code>.
     */
    public final FindingsProgesternrezeptor FINDINGS_PROGESTERNREZEPTOR = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsProgesternrezeptor.FINDINGS_PROGESTERNREZEPTOR;

    /**
     * The table <code>patient_repository_saat_mamma.findings_with_rezeptor</code>.
     */
    public final FindingsWithRezeptor FINDINGS_WITH_REZEPTOR = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsWithRezeptor.FINDINGS_WITH_REZEPTOR;

    /**
     * The table <code>patient_repository_saat_mamma.rezeptor_names</code>.
     */
    public final RezeptorNames REZEPTOR_NAMES = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.RezeptorNames.REZEPTOR_NAMES;

    /**
     * No further instances allowed
     */
    private PatientRepositorySaatMamma() {
        super("patient_repository_saat_mamma", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.REZEPTOR_NAMES_REZEPTOR_NAMES_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FindingsHer2neu.FINDINGS_HER2NEU,
            FindingsOestrogenrezeptor.FINDINGS_OESTROGENREZEPTOR,
            FindingsProgesternrezeptor.FINDINGS_PROGESTERNREZEPTOR,
            FindingsWithRezeptor.FINDINGS_WITH_REZEPTOR,
            RezeptorNames.REZEPTOR_NAMES);
    }
}
