/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma;


import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsWithRezeptor;
import at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.RezeptorNames;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in patient_repository_saat_mamma
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>patient_repository_saat_mamma.findings_with_rezeptor</code>.
     */
    public static final FindingsWithRezeptor FINDINGS_WITH_REZEPTOR = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.FindingsWithRezeptor.FINDINGS_WITH_REZEPTOR;

    /**
     * The table <code>patient_repository_saat_mamma.rezeptor_names</code>.
     */
    public static final RezeptorNames REZEPTOR_NAMES = at.medunigraz.pathology.bibbox.datatools.jooq.patient_repository_saat_mamma.tables.RezeptorNames.REZEPTOR_NAMES;
}
