/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.saat;


import at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.Dictionary;
import at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryLinkDictionary;
import at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryLinkDictionaryOrig;
import at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryOrig;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in saat
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>saat.dictionary</code>.
     */
    public static final Dictionary DICTIONARY = at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.Dictionary.DICTIONARY;

    /**
     * The table <code>saat.dictionary_link_dictionary</code>.
     */
    public static final DictionaryLinkDictionary DICTIONARY_LINK_DICTIONARY = at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryLinkDictionary.DICTIONARY_LINK_DICTIONARY;

    /**
     * The table <code>saat.dictionary_link_dictionary_orig</code>.
     */
    public static final DictionaryLinkDictionaryOrig DICTIONARY_LINK_DICTIONARY_ORIG = at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryLinkDictionaryOrig.DICTIONARY_LINK_DICTIONARY_ORIG;

    /**
     * The table <code>saat.dictionary_orig</code>.
     */
    public static final DictionaryOrig DICTIONARY_ORIG = at.medunigraz.pathology.bibbox.datatools.jooq.saat.tables.DictionaryOrig.DICTIONARY_ORIG;
}
