/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.PoGleason;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.records.PoGleasonRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>prostate_google</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PoGleasonRecord, Integer> IDENTITY_PO_GLEASON = Identities0.IDENTITY_PO_GLEASON;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PoGleasonRecord> PO_GLEASON_PKEY = UniqueKeys0.PO_GLEASON_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PoGleasonRecord, Integer> IDENTITY_PO_GLEASON = Internal.createIdentity(PoGleason.PO_GLEASON, PoGleason.PO_GLEASON.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PoGleasonRecord> PO_GLEASON_PKEY = Internal.createUniqueKey(PoGleason.PO_GLEASON, "po_gleason_pkey", PoGleason.PO_GLEASON.ID);
    }
}
