/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in prostate_google
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>prostate_google.po_gleason_id_seq</code>
     */
    public static final Sequence<Long> PO_GLEASON_ID_SEQ = new SequenceImpl<Long>("po_gleason_id_seq", ProstateGoogle.PROSTATE_GOOGLE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
