/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.Casedataprostate;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.PoGleason;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.ProstateCaPos;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.ProstateCases;
import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.RandomCases;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in prostate_google
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>prostate_google.casedataprostate</code>.
     */
    public static final Casedataprostate CASEDATAPROSTATE = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.Casedataprostate.CASEDATAPROSTATE;

    /**
     * The table <code>prostate_google.po_gleason</code>.
     */
    public static final PoGleason PO_GLEASON = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.PoGleason.PO_GLEASON;

    /**
     * The table <code>prostate_google.prostate_ca_pos</code>.
     */
    public static final ProstateCaPos PROSTATE_CA_POS = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.ProstateCaPos.PROSTATE_CA_POS;

    /**
     * The table <code>prostate_google.prostate_cases</code>.
     */
    public static final ProstateCases PROSTATE_CASES = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.ProstateCases.PROSTATE_CASES;

    /**
     * The table <code>prostate_google.random_cases</code>.
     */
    public static final RandomCases RANDOM_CASES = at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.RandomCases.RANDOM_CASES;
}
