/*
 * This file is generated by jOOQ.
 */
package at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.records;


import at.medunigraz.pathology.bibbox.datatools.jooq.prostate_google.tables.ProstateCases;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProstateCasesRecord extends TableRecordImpl<ProstateCasesRecord> implements Record18<Long, String, Date, String, String, String, String, Short, Integer, Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1537276586;

    /**
     * Setter for <code>prostate_google.prostate_cases.vhistonumberid</code>.
     */
    public void setVhistonumberid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.vhistonumberid</code>.
     */
    public Long getVhistonumberid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.gewinnungsart</code>.
     */
    public void setGewinnungsart(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.gewinnungsart</code>.
     */
    public String getGewinnungsart() {
        return (String) get(1);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.eingangsdatum</code>.
     */
    public void setEingangsdatum(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.eingangsdatum</code>.
     */
    public Date getEingangsdatum() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.material</code>.
     */
    public void setMaterial(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.material</code>.
     */
    public String getMaterial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.materialzusatz</code>.
     */
    public void setMaterialzusatz(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.materialzusatz</code>.
     */
    public String getMaterialzusatz() {
        return (String) get(4);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.t</code>.
     */
    public void setT(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.t</code>.
     */
    public String getT() {
        return (String) get(5);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.n</code>.
     */
    public void setN(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.n</code>.
     */
    public String getN() {
        return (String) get(6);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.age</code>.
     */
    public void setAge(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.age</code>.
     */
    public Short getAge() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.survivalindays</code>.
     */
    public void setSurvivalindays(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.survivalindays</code>.
     */
    public Integer getSurvivalindays() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.status</code>.
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.stage</code>.
     */
    public void setStage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.stage</code>.
     */
    public String getStage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.diagnose</code>.
     */
    public void setDiagnose(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.diagnose</code>.
     */
    public String getDiagnose() {
        return (String) get(11);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.makroskopiebeschreibung</code>.
     */
    public void setMakroskopiebeschreibung(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.makroskopiebeschreibung</code>.
     */
    public String getMakroskopiebeschreibung() {
        return (String) get(12);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.histologiebeschreibung</code>.
     */
    public void setHistologiebeschreibung(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.histologiebeschreibung</code>.
     */
    public String getHistologiebeschreibung() {
        return (String) get(13);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.mikroskopiebeschreibung</code>.
     */
    public void setMikroskopiebeschreibung(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.mikroskopiebeschreibung</code>.
     */
    public String getMikroskopiebeschreibung() {
        return (String) get(14);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.mpbeschreibung</code>.
     */
    public void setMpbeschreibung(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.mpbeschreibung</code>.
     */
    public String getMpbeschreibung() {
        return (String) get(15);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.schnellschnittdiagnose</code>.
     */
    public void setSchnellschnittdiagnose(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.schnellschnittdiagnose</code>.
     */
    public String getSchnellschnittdiagnose() {
        return (String) get(16);
    }

    /**
     * Setter for <code>prostate_google.prostate_cases.mpdiagnose</code>.
     */
    public void setMpdiagnose(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>prostate_google.prostate_cases.mpdiagnose</code>.
     */
    public String getMpdiagnose() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, Date, String, String, String, String, Short, Integer, Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, String, Date, String, String, String, String, Short, Integer, Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProstateCases.PROSTATE_CASES.VHISTONUMBERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProstateCases.PROSTATE_CASES.GEWINNUNGSART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return ProstateCases.PROSTATE_CASES.EINGANGSDATUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProstateCases.PROSTATE_CASES.MATERIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProstateCases.PROSTATE_CASES.MATERIALZUSATZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProstateCases.PROSTATE_CASES.T;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ProstateCases.PROSTATE_CASES.N;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return ProstateCases.PROSTATE_CASES.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ProstateCases.PROSTATE_CASES.SURVIVALINDAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return ProstateCases.PROSTATE_CASES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ProstateCases.PROSTATE_CASES.STAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ProstateCases.PROSTATE_CASES.DIAGNOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return ProstateCases.PROSTATE_CASES.MAKROSKOPIEBESCHREIBUNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return ProstateCases.PROSTATE_CASES.HISTOLOGIEBESCHREIBUNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return ProstateCases.PROSTATE_CASES.MIKROSKOPIEBESCHREIBUNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return ProstateCases.PROSTATE_CASES.MPBESCHREIBUNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return ProstateCases.PROSTATE_CASES.SCHNELLSCHNITTDIAGNOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return ProstateCases.PROSTATE_CASES.MPDIAGNOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getVhistonumberid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGewinnungsart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getEingangsdatum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMaterial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMaterialzusatz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getT();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getN();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getSurvivalindays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getStage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getMakroskopiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getHistologiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getMikroskopiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getMpbeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getSchnellschnittdiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getMpdiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getVhistonumberid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGewinnungsart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getEingangsdatum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMaterial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMaterialzusatz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getT();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getN();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSurvivalindays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMakroskopiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getHistologiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getMikroskopiebeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getMpbeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getSchnellschnittdiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getMpdiagnose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value1(Long value) {
        setVhistonumberid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value2(String value) {
        setGewinnungsart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value3(Date value) {
        setEingangsdatum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value4(String value) {
        setMaterial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value5(String value) {
        setMaterialzusatz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value6(String value) {
        setT(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value7(String value) {
        setN(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value8(Short value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value9(Integer value) {
        setSurvivalindays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value11(String value) {
        setStage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value12(String value) {
        setDiagnose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value13(String value) {
        setMakroskopiebeschreibung(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value14(String value) {
        setHistologiebeschreibung(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value15(String value) {
        setMikroskopiebeschreibung(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value16(String value) {
        setMpbeschreibung(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value17(String value) {
        setSchnellschnittdiagnose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord value18(String value) {
        setMpdiagnose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProstateCasesRecord values(Long value1, String value2, Date value3, String value4, String value5, String value6, String value7, Short value8, Integer value9, Integer value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProstateCasesRecord
     */
    public ProstateCasesRecord() {
        super(ProstateCases.PROSTATE_CASES);
    }

    /**
     * Create a detached, initialised ProstateCasesRecord
     */
    public ProstateCasesRecord(Long vhistonumberid, String gewinnungsart, Date eingangsdatum, String material, String materialzusatz, String t, String n, Short age, Integer survivalindays, Integer status, String stage, String diagnose, String makroskopiebeschreibung, String histologiebeschreibung, String mikroskopiebeschreibung, String mpbeschreibung, String schnellschnittdiagnose, String mpdiagnose) {
        super(ProstateCases.PROSTATE_CASES);

        set(0, vhistonumberid);
        set(1, gewinnungsart);
        set(2, eingangsdatum);
        set(3, material);
        set(4, materialzusatz);
        set(5, t);
        set(6, n);
        set(7, age);
        set(8, survivalindays);
        set(9, status);
        set(10, stage);
        set(11, diagnose);
        set(12, makroskopiebeschreibung);
        set(13, histologiebeschreibung);
        set(14, mikroskopiebeschreibung);
        set(15, mpbeschreibung);
        set(16, schnellschnittdiagnose);
        set(17, mpdiagnose);
    }
}
